### ISSUE TITLE
Code is a mess and there are no tests

### ISSUE THREAD

**Issue by PandaWhisperer** [pandastrike/panda-cluster-kick#2]
The kick server code is, quite frankly, a mess. I know it's not outside facing or whatever, and maybe not even a particularly high priority piece of code, but for our own sanity's sake, we should apply the same engineering principles here as we apply to any other piece of software we produce. 

That is, the code is
- organized
- readable
- has at least a basic test suite to demonstrate it's working

**NOTE:** this ticket is just for me. I'M FIXING THE GODDAMN TICKET. If you're offended, it's your fault, not mine.

**Comment by freeformflow** [comment]
@PandaWhisperer, I agree that panda-kick is rough.  Since it's passed the proof-of-concept test from Dan, let's go ahead and create a formalized API server using PBX.  It should only take a couple days, and we want to make sure this is reliable since it underpins our ability to deploy other services. 

Since panda-kick is part of the "wiring up" that Huxley clusters perform, and you've been dealing with that for the ELK stack mixins, I think this work dove-tails nicely.  This is Ticket #24 on Huxley.  Let's make it part of your Iteration Alpha-02 work, please.  I'll copy this text there.

Also, please let me know if you'd like me to walk you through any code or intentions.

**Comment by PandaWhisperer** [comment]
Closing in favor of https://github.com/pandastrike/huxley/issues/24
